-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
--
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
-- insert into article values ((select nextval('HIBERNATE_SEQUENCE')), (select concat('cucu', rand())), (select concat('cucu', rand())), 0);
